#!/bin/sh
set -e
PATH="/usr/local/bin:$PATH"
trap "rm -f .git/tags.$$" EXIT
ctags --tag-relative -Rf.git/tags.$$ --exclude=.git --exclude=coverage --exclude=vendor --exclude=report --exclude=files --exclude=public/assets
mv .git/tags.$$ .git/tags
