#!/bin/sh
set -e
PATH="/usr/local/bin:$PATH"
trap "rm -f $GIT_DIR/tags.$$" EXIT
ctags --tag-relative -Rf$GIT_DIR/tags.$$ --exclude=$GIT_DIR --exclude=coverage --exclude=node_modules --exclude=vendor --exclude=report --exclude=files --exclude="public/assets*"
mv $GIT_DIR/tags.$$ $GIT_DIR/tags
